name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: "14"
          cache: "pnpm"

      - name: Install Dependencies with pnpm
        if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm test
